### ISSUE TITLE
Add reprozip-jupyter to the docs

### ISSUE THREAD

**Issue by VickySteeves** [ViDA-NYU/reprozip#277] opened 2017-10-06 17:07 UTC
As of now, the only places where folks can learn how to use/install our Jupyter plugin are the [YouTube video ](https://www.youtube.com/watch?v=Y8YmGVYHhS8) and the [SciPy slides](https://vickysteeves.gitlab.io/2017-SciPy/#/20). We should add this to the docs ([which apparently are great](https://twitter.com/pitman_mark/status/916161333724299264)!).

**Comment by remram44** [comment] 2017-10-06 18:50
Duplicate of #262 (that you're assigned to 🙃)

**Closed** 2017-10-06 18:50 UTC
Labels: C-doc, R-duplicate
