### ISSUE TITLE
Misses inputs: process used unhandled system call openat(-100, "foo")

### ISSUE THREAD

**Issue by yarikoptic** [ViDA-NYU/reprozip#293] opened 2018-03-19 20:25 UTC
thank you for the reprozip!
While exploring it more we ran into "input" files being not traced on my laptop (Debian sid/unstable with 4.15.0-1-amd64 kernel) while it worked just fine for @kyleam on his Debian stable. ~/.reprozip/log kindly informed me that many interesting files were not traced, for which there was a number of those log messages:
```shell
$> tail ~/.reprozip/log
[REPROZIP] 16:10:08.359 INFO: [28405] process used unhandled system call openat(-100, "/usr/lib/locale/en_US.utf8/LC_COLLATE")
[REPROZIP] 16:10:08.359 INFO: [28405] process used unhandled system call openat(-100, "/usr/lib/locale/en_US.utf8/LC_TIME")
[REPROZIP] 16:10:08.359 INFO: [28405] process used unhandled system call openat(-100, "/usr/lib/locale/en_US.utf8/LC_NUMERIC")
[REPROZIP] 16:10:08.359 INFO: [28405] process used unhandled system call openat(-100, "/usr/lib/locale/en_US.utf8/LC_CTYPE")
[REPROZIP] 16:10:08.360 INFO: [28405] process used unhandled system call openat(-100, "foo")
[REPROZIP] 16:10:08.384 INFO: Program completed
[REPROZIP] 16:10:08.421 INFO: Running filter plugin builtin
[REPROZIP] 16:10:08.422 INFO: Running filter plugin python
[REPROZIP] 16:10:08.544 INFO: Identifying Debian packages for 29 files...
[REPROZIP] 16:10:17.324 INFO: 8 packages with 12 files, and 17 other files
```
unfortunately my cfoo is too lame to offer any sensible PR, so I am at your mercy with this issue.

Thank you in advance.  ReproZip is from current 1.0.11-14-gb0504b5

**Comment by remram44** [comment] 2018-03-19 20:37
Hi Yaroslav,

Indeed this is supposed to be supported. `-100` is `AT_FDWD`, yet we missed the condition at line 783 to hit line 821. What is going on?

https://github.com/ViDA-NYU/reprozip/blob/b0504b532f0c02792d273918480f6bedaa13c92a/reprozip/native/syscalls.c#L775-L784

I can try to reproduce on Debian unstable. Thank you for the detailed report!

**Comment by remram44** [comment] 2018-03-19 21:51
Indeed this looks like a change in the kernel interface. The RDI register used to contain `0xffffffffffffff9c`, and now is `0xffffff9c`.

I also need to rule out changes in the compiler.

VM: gcc=7.2.0-1d1 gcc-7=7.3.0-11 linux=4.14.0-3-amd64 (Debian sid)
Laptop: gcc=7.2.0-1ubuntu1 gcc-7=7.2.0-8ubuntu3.2 linux=4.13.0-37-generic (Ubuntu 17.10 Artful)

**Comment by remram44** [comment] 2018-03-19 22:30
It seems that everything gets correctly passed as a 64-bit signed number (for example, return values), except that `AT_FDCWD`. I do not understand...

**Comment by remram44** [comment] 2018-03-19 22:40
The same test executable tested with the same `_pytracer.so` exhibits different behavior so I'm going to have to assume this is a change in the kernel (or libc). I think I'm just going to have to handle both values in `syscall_xxx_at` (and possibly everywhere else a negative value is expected), the one correctly sign-extended to 64 bits, and the one extended to 32 bits.

I'll commit a fix soon. I'm still very puzzled by this behavior.

**Comment by yarikoptic** [comment] 2018-03-20 14:22
Let me know if I could be of any help. Cheers!

**Comment by remram44** [comment] 2018-03-20 17:19
Can you try again using the current `1.0.x` branch? Hopefully you don't see "`unhandled system call openat(-100,`" anymore.

**Comment by yarikoptic** [comment] 2018-03-20 17:57
YES! it fixed it, no more "unhandled" log messages and `inputs_outputs` correctly lists both files in my tiny example. Thank you!

**Comment by remram44** [comment] 2018-03-20 21:19
Great news! Glad I could address that. I also added another improvement to `openat()`, so once I do proper testing, I will probably release a 1.0.12.

**Comment by remram44** [comment] 2018-03-20 21:19
Fixed by f74af4e7.

**Closed by remram44** 2018-03-20 21:19 UTC
Labels: C-tracer (C), T-bug

**Comment by remram44** [comment] 2018-08-29 20:18
@ghisvail sorry to ping you on this, but is there a timetable for updating the Debian package for reprozip? This bug seems to affect a few people and is fixed in `1.0.12` (Debian and Ubuntu currently have `1.0.10`). Thanks a lot!

**Comment by yarikoptic** [comment] 2018-08-30 15:50
ok, updated, pushed 1.0.14-1 to salsa, uploaded to Debian and backports for recentish debian/ubuntu to neurodebian.

**Comment by remram44** [comment] 2018-08-31 14:30
Wow, thanks! That was fast :flushed:

I got a lot of build failure emails, you might want to [merge this](https://salsa.debian.org/science-team/reprozip/merge_requests/1) :wink:
